-- 1. Create Forum Post Likes Table
create table if not exists public.forum_post_likes (
    id bigint generated by default as identity primary key,
    post_id bigint references public.forum_posts(id) on delete cascade not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    unique(post_id, user_id)
);

-- Enable RLS
alter table public.forum_post_likes enable row level security;

-- Policies for Likes (Drop first to avoid conflicts if re-running)
drop policy if exists "Likes are viewable by everyone" on public.forum_post_likes;
create policy "Likes are viewable by everyone"
    on public.forum_post_likes for select
    using (true);

drop policy if exists "Authenticated users can insert likes" on public.forum_post_likes;
create policy "Authenticated users can insert likes"
    on public.forum_post_likes for insert
    with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own likes" on public.forum_post_likes;
create policy "Users can delete their own likes"
    on public.forum_post_likes for delete
    using (auth.uid() = user_id);

-- 2. Add Tags column to forum_posts if not exists
do $$
begin
    if not exists (select 1 from information_schema.columns where table_name = 'forum_posts' and column_name = 'tags') then
        alter table public.forum_posts add column tags text[] default '{}';
    end if;
end $$;

-- 3. RPC Functions for Like Counts (Atomic updates)
create or replace function increment_post_likes(post_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.forum_posts
  set like_count = coalesce(like_count, 0) + 1
  where id = post_id;
end;
$$;

create or replace function decrement_post_likes(post_id bigint)
returns void
language plpgsql
security definer
as $$
begin
  update public.forum_posts
  set like_count = greatest(coalesce(like_count, 0) - 1, 0)
  where id = post_id;
end;
$$;

-- 4. RPC Function to get Popular Tags
create or replace function get_popular_tags()
returns table (tag text, count bigint)
language sql
security definer
as $$
  select unnest(tags) as tag, count(*) as count
  from public.forum_posts
  where status = 'published'
  group by tag
  order by count desc
  limit 10;
$$;

-- 5. RPC Function to get Active Users (Top 5 by message count)
create or replace function get_top_active_users()
returns table (
  user_id uuid,
  first_name text,
  last_name text,
  avatar_url text,
  is_bot boolean,
  message_count bigint
)
language sql
security definer
as $$
  select 
    p.id as user_id,
    p.first_name,
    p.last_name,
    p.avatar_url,
    p.is_bot,
    count(c.id) as message_count
  from public.profiles p
  join public.forum_comments c on c.user_id = p.id
  where c.status = 'published'
  group by p.id, p.first_name, p.last_name, p.avatar_url, p.is_bot
  order by message_count desc
  limit 5;
$$;
